Python — List Operations

In [102]:
# Membuat list
data = [10, 20, 999, True, 3.14]
# Akses & slicing
print(data[0]) # → 10
print(data[-1]) # → 3.14 (dari belakang)
print(data[1:3]) # → [20, 'Python']
# Manipulasi
data.append(99) # tambah di akhir
data.insert(1, 55) # sisipkan di posisi 1
data.remove(20) # hapus nilai pertama = 20
data.sort() # urutkan (jika tipe sama)

10
3.14
[20, 999]


Python — Dictionary Operations

In [103]:
mahasiswa = {
'nama': 'Naufal Julio',
'nim': '220401010028',
'usia': 22,
'prodi': 'Informatika',
'ipk': 3.85
}
# Akses nilai
print(mahasiswa['nama']) # → 'Budi Santoso'
print(mahasiswa.get('usia', 0)) # default jika key tak ada
# Update dan hapus
mahasiswa['angkatan'] = 2024 # tambah key baru
del mahasiswa['nim'] # hapus key

Naufal Julio
22


Python — Membuat NumPy Array

In [104]:
import numpy as np
# Dari list Python
a1D = np.array([1, 2, 3, 4, 5]) # 1D
a2D = np.array([[1,2,3],[4,5,6]]) # 2D
# Array dengan nilai inisial
zeros = np.zeros((3, 4)) # nol semua
ones = np.ones((2, 3)) # satu semua
eye = np.eye(4) # matriks identitas
full = np.full((2, 2), 7) # nilai konstan
# Sequence
arange = np.arange(0, 20, 2) # 0,2,4,...18
linsp = np.linspace(0, 1, 11) # 11 titik merata
# Array acak (reproducible)
rng = np.random.default_rng(seed=42)
rand_int = rng.integers(0, 100, (3, 4))
rand_flt = rng.normal(loc=0, scale=1, size=(100,))

Python — NumPy Vektorisasi & Statistik

In [105]:
# Operasi aritmetika vektorisasi
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(a + b) # → [11 22 33 44 55]
print(a * b) # → [10 40 90 160 250]
print(a ** 3) # → [1 4 9 16 25]

# Universal functions (ufuncs)
np.sqrt(a) # akar kuadrat tiap elemen
np.exp(a) # eksponensial (e^x)
np.log(b) # logaritma natural

# Fungsi statistik
data = rng.normal(0, 1, 1000)
print(f'Mean: {np.mean(data):.4f}')
print(f'Std: {np.std(data):.4f}')
print(f'Min: {np.min(data):.4f}')
print(f'Max: {np.max(data):.4f}')
print(f'Q1: {np.percentile(data,25):.4f}')
print(f'Q3: {np.percentile(data,75):.4f}')

[11 22 33 44 55]
[ 10  40  90 160 250]
[  1   8  27  64 125]
Mean: -0.0163
Std: 1.0008
Min: -3.6484
Max: 3.1789
Q1: -0.6897
Q3: 0.6163


Python — Pandas Series

In [106]:
import pandas as pd
# Series dari list — index default 0,1,2...
s1 = pd.Series([85, 92, 78, 95, 88])
# Series dengan index kustom
nilai = pd.Series(
[85, 92, 78, 95],
index=['Alice','Bob','Caca','Dina']
)
print(nilai['Bob']) # → 92
print(nilai[nilai>80]) # filter
print(nilai.mean()) # → 87.5
print(nilai.describe()) # statistik lengkap

92
Alice    85
Bob      92
Dina     95
dtype: int64
87.5
count     4.000000
mean     87.500000
std       7.593857
min      78.000000
25%      83.250000
50%      88.500000
75%      92.750000
max      95.000000
dtype: float64


Python — Membuat Pandas DataFrame

In [107]:
# Membuat DataFrame dari dictionary
data = {
'nama': ['Ali','Budi','Caca','Dina'],
'usia': [22, 25, 21, 23],
'kota': ['Jakarta','Bandung','Surabaya','Medan'],
'ipk': [3.8, 3.5, 3.9, 3.7]
}
df = pd.DataFrame(data)
# Informasi dasar
print(df.shape) # → (4, 4)
print(df.dtypes) # tipe data per kolom
print(df.columns) # nama-nama kolom

(4, 4)
nama     object
usia      int64
kota     object
ipk     float64
dtype: object
Index(['nama', 'usia', 'kota', 'ipk'], dtype='object')


Python — pd.read_csv()

In [108]:
# Memuat dari file lokal
# df = pd.read_csv('data/penjualan.csv')
# Memuat dari URL (dataset publik)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

print(df.shape)      # jumlah baris dan kolom
print(df.columns)    # nama kolom
print(df.head())     # 5 baris pertama

(891, 12)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C 

**MUHAMMAD NAUFAL JULIO | 220401010028**

---
**LATIHAN**


In [109]:
 import pandas as pd
 import numpy as np

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

In [110]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


### Q1 Berapa jumlah baris dan kolom pada dataset Titanic? Kolom apa saja yang tersedia?

In [112]:
print(df.shape)
print("\n")
print(df.columns)
print("\nJadi jumlah barisnya adalah 891 dan jumlah kolomnya adalah 12")

(891, 12)


Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

Jadi jumlah barisnya adalah 891 dan jumlah kolomnya adalah 12


### Q1 Kolom mana saja yang memiliki missing values? Berapa jumlah dan proporsinya (%) per kolom?

In [113]:
missing = df.isnull().sum()
persentase = (missing / len(df)) * 100

hasil_missing = pd.DataFrame({
    'Jumlah Missing': missing,
    'Persentase (%)': persentase
})

print(hasil_missing)

print("\nJadi kolom yang memiliki missing values adalah Age, Cabin, dan Embarked")
print("Jumlah missing values pada kolom Age adalah 177, Cabin adalah 687, dan Embarked adalah 2")
print("Persentase missing values pada kolom Age adalah 19.875000%, Cabin adalah 77.100000%, dan Embarked adalah 0.222222%")

             Jumlah Missing  Persentase (%)
PassengerId               0        0.000000
Survived                  0        0.000000
Pclass                    0        0.000000
Name                      0        0.000000
Sex                       0        0.000000
Age                     177       19.865320
SibSp                     0        0.000000
Parch                     0        0.000000
Ticket                    0        0.000000
Fare                      0        0.000000
Cabin                   687       77.104377
Embarked                  2        0.224467

Jadi kolom yang memiliki missing values adalah Age, Cabin, dan Embarked
Jumlah missing values pada kolom Age adalah 177, Cabin adalah 687, dan Embarked adalah 2
Persentase missing values pada kolom Age adalah 19.875000%, Cabin adalah 77.100000%, dan Embarked adalah 0.222222%


### Q3 Berapa persen penumpang yang selamat (Survived=1)? Gunakan operasi NumPy atau Pandas.

In [114]:
persen_selamat = df['Survived'].mean() * 100
print(f"Persentase penumpang selamat: {persen_selamat:.2f}%")
print("\n Jadi persentase dari penumpanh yang selamat adalah 38.38%")

Persentase penumpang selamat: 38.38%

 Jadi persentase dari penumpanh yang selamat adalah 38.38%


### Q4 Filter penumpang wanita dari kelas 1 (Pclass=1). Berapa jumlahnya dan berapa rata-rata usianya?

In [115]:
wanita_class1 = df[(df['Sex'] == 'female') & (df['Pclass'] == 1)]

jumlah = len(wanita_class1)
rata_usia = wanita_class1['Age'].mean()

print("Jadi jumlah penumpanh wanita dari kelas 1 adalah :", jumlah)
print("dengan rata-rata usia:", rata_usia)


Jadi jumlah penumpanh wanita dari kelas 1 adalah : 94
dengan rata-rata usia: 34.61176470588235


### Q5 Gunakan groupby untuk menghitung tingkat keselamatan (mean Survived) per kelas penumpang. Kelas mana yang paling tinggi?

In [116]:
survived = df.groupby('Pclass')['Survived'].mean()

print(survived)
print("\nTingkat keselamatan tertinggi terjadi pada kelas", survived.idxmax(), "dengan tingkat keselamatan sebesar ", survived.max())

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

Tingkat keselamatan tertinggi terjadi pada kelas 1 dengan tingkat keselamatan sebesar  0.6296296296296297


### Q6 Buat analisis tambahan berdasarkan variabel lain yang Anda anggap menarik. Sertakan interpretasi singkat.

In [128]:
print("Untuk analisis tambahan, saya menggunakan variabel kategori keluarga Besar, Kecil, dan Sendirian.")
print("Berikut data nya :")
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1

def kategori_keluarga(x):
    if x == 1:
        return "Sendiri"
    elif x <= 4:
        return "Kecil"
    else:
        return "Besar"

df["Kategori Keluarga"] = df["FamilySize"].apply(kategori_keluarga)

hasil = df.groupby("Kategori Keluarga")["Survived"].mean() * 100

print(hasil)
print("Catatan : Keluarga kecil adalah keluarga kurang dari 4 orang, sedangkan Keluarga Besar adalah keluarga lebih dari 4 orang")
print("\nPenumpang yang bepergian dengan keluarga kecil cenderung memiliki tingkat keselamatan lebih tinggi")
print("dibandingkan penumpang yang bepergian sendiri atau dalam keluarga besar.")
print("Hal ini mungkin disebabkan karena anggota keluarga kecil dapat saling membantu saat evakuasi,")
print("sedangkan keluarga besar lebih sulit untuk tetap bersama dalam situasi darurat.")

Untuk analisis tambahan, saya menggunakan variabel kategori keluarga Besar, Kecil, dan Sendirian.
Berikut data nya :
Kategori Keluarga
Besar      16.129032
Kecil      57.876712
Sendiri    30.353818
Name: Survived, dtype: float64
Catatan : Keluarga kecil adalah keluarga kurang dari 4 orang, sedangkan Keluarga Besar adalah keluarga lebih dari 4 orang

Penumpang yang bepergian dengan keluarga kecil cenderung memiliki tingkat keselamatan lebih tinggi
dibandingkan penumpang yang bepergian sendiri atau dalam keluarga besar.
Hal ini mungkin disebabkan karena anggota keluarga kecil dapat saling membantu saat evakuasi,
sedangkan keluarga besar lebih sulit untuk tetap bersama dalam situasi darurat.
